server:
  port: 8080
  servlet:
    session:
      timeout: 30m

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

spring:
  application:
    name: gulimall-product # 服务名称
  profiles:
    active: dev #开发环境，这里是dev
  cloud:
    nacos:
      server-addr: nacos-service.gulimall:8848
      config:
        server-addr: nacos-service.gulimall:8848
        file-extension: yaml # 文件后缀名
        namespace: product
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: sentinel-service.gulimall:8333
  #服务追踪
  zipkin:
    base-url: http://zipkin-service.gulimall:9411/
    discovery-client-enabled: false # 关闭服务发现，否则 Spring Cloud 会把 zipkin 的 url 当做服务名称
    sender:
      type: web # 设置使用 http 的方式传输数据
  #配置采样器
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为 100%，默认为 0.1，即 10%
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-master.gulimall:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: redis.gulimall
  session:
    store-type: redis
  cache:
    type: redis
    #    cache-names: qq,
    redis:
      time-to-live: 3600000 #毫秒为单位
      #      key-prefix: CACHE_ #如果指定了前缀就用我们指定的前缀，如果没有就默认使用缓存的名字作为前缀
      use-key-prefix: true
      cache-null-values: true #是否缓存空值，防止缓存穿透

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      #      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.hpf.gulimall: error
    #开启debug日志
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'