server:
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
  session:
    store-type: redis
  cache:
    type: redis
    #    cache-names: qq,
    redis:
      time-to-live: 3600000 #毫秒为单位
      #      key-prefix: CACHE_ #如果指定了前缀就用我们指定的前缀，如果没有就默认使用缓存的名字作为前缀
      use-key-prefix: true
      cache-null-values: true #是否缓存空值，防止缓存穿透

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      #      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.hpf.gulimall: error

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10