kind: Service
apiVersion: v1
metadata:
  name: gulimall-cart
  namespace: gulimall
  labels:
    app: gulimall-cart
    version: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 20003
  selector:
    app: gulimall-cart
  type: NodePort
  sessionAffinity: None