kind: Service
apiVersion: v1
metadata:
  name: gulimall-member
  namespace: gulimall
  labels:
    app: gulimall-member
    version: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 20009
  selector:
    app: gulimall-member
  type: NodePort
  sessionAffinity: None