kind: Deployment
apiVersion: apps/v1
metadata:
  name: gulimall-product
  namespace: gulimall
  labels:
    app: gulimall-product
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gulimall-product
      version: v1
  template:
    metadata:
      labels:
        app: gulimall-product
        version: v1
    spec:
      containers:
        - name: gulimall-product
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$TAG_NAME
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600