kind: Service
apiVersion: v1
metadata:
  name: gulimall-product
  namespace: gulimall
  labels:
    app: gulimall-product
    version: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 20013
  selector:
    app: gulimall-product
  type: NodePort
  sessionAffinity: None