server:
  port: 25000

spring:
  redis:
    host: 192.168.56.10
    port: 6379
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
  #配置异步任务线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
  session:
    store-type: redis

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
