spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 970512
  # RabbitMQ配置
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    # 虚拟主机配置
    virtual-host: /
    # 开启发送端消息抵达Broker确认
    publisher-confirm-type: correlated
    # 开启发送端消息抵达Queue确认
    publisher-returns: true
    # 只要消息抵达Queue，就会异步发送优先回调returnFirm
    template:
      mandatory: true
    # 手动ack消息，不使用默认的消费端确认
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis

#seata:
#  enabled: true # 1.0新特性，需要依赖seata-spring-boot-starter 默认为true
#  enable-auto-data-source-proxy: true  # 牵扯到回滚
#  tx-service-group: my_test_tx_group  # 需要与config.txt中的 service.vgroupMapping.seata_test_group=default保持一致
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      username: nacos
#      password: nacos
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      username: nacos
#      password: nacos
#      namespace: seata
#  service:
#    vgroup-mapping:
#      my_test_tx_group: default # 需要与config.txt中的 service.vgroupMapping.seata_test_group=default 保持一致
#    disable-global-transaction: false
#  client:
#    rm:
#      report-success-enable: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10
