kind: Service
apiVersion: v1
metadata:
  name: gulimall-third-party
  namespace: gulimall
  labels:
    app: gulimall-third-party
    version: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 20019
  selector:
    app: gulimall-third-party
  type: NodePort
  sessionAffinity: None