server:
  port: 40000

spring:
  #服务追踪
  zipkin:
    base-url: http://192.168.56.10:9411/
    discovery-client-enabled: false # 关闭服务发现，否则 Spring Cloud 会把 zipkin 的 url 当做服务名称
    sender:
      type: web # 设置使用 http 的方式传输数据
  #配置采样器
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为 100%，默认为 0.1，即 10%
  redis:
    port: 6379
    host: 192.168.56.10
  session:
    store-type: redis

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10