server:
  port: 40000

spring:
  redis:
    port: 6379
    host: 192.168.56.10
  session:
    store-type: redis

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10